version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - HOST=0.0.0.0
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
    volumes:
      - ./backend:/app
      - /app/venv
    depends_on:
      - mongodb
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    platform: linux/amd64
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
